In [3]:
import numpy as np

data = [[1, 6, 7, 9], [5, 4, 2, 8]]
arr2 = np.array(data)
print(arr2.ndim) 
print(arr2.shape)  


2
(2, 4)


In [4]:
array = np.array([[0,1,0],[7,3,9]])

In [5]:
array

array([[0, 1, 0],
       [7, 3, 9]])

In [6]:
array = np.eye(4)

In [7]:
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
array = np.zeros((3,2))

In [9]:
array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
array = np.arange(0, 7, 4)

In [11]:
array

array([0, 4])

In [12]:
array = np.ones((2,3))

In [13]:
array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
array = np.random.randint(0, 8, (3,2))

In [16]:
arr = np.array([[8., 7., 10.], [5., 3., 6.]])
print(arr)

[[ 8.  7. 10.]
 [ 5.  3.  6.]]


In [17]:
print(arr * arr)

[[ 64.  49. 100.]
 [ 25.   9.  36.]]


In [18]:
print(arr - arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
arr = np.array([[8., 7., 10.], [5., 3., 6.]])
print(arr)

[[ 8.  7. 10.]
 [ 5.  3.  6.]]


In [20]:
print(arr **2)

[[ 64.  49. 100.]
 [ 25.   9.  36.]]


In [21]:
arr2 = np.array([[6., 1., 5.], [10., 5., 11.]])
print(arr2)

[[ 6.  1.  5.]
 [10.  5. 11.]]


In [22]:
print(arr2 > arr)

[[False False False]
 [ True  True  True]]


In [23]:
arr = np.arange(16)
print(arr)        

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [24]:
print(arr[7])   

7


In [25]:
print(arr[5:8])

[5 6 7]


In [26]:
arr[5:8] = 11
print(arr)

[ 0  1  2  3  4 11 11 11  8  9 10 11 12 13 14 15]


In [27]:
arr = np.arange(10)
print(arr)                     

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr_slice = arr[5:8]
print(arr_slice)

[5 6 7]


In [29]:
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4     5 12345     7     8     9]


In [30]:
arr_slice[:] = 52
print(arr)

[ 0  1  2  3  4 52 52 52  8  9]


In [31]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])       

[7 8 9]


In [33]:
print(arr2d[0][2])     

3


In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [54]:
arr2d_slice = arr2d[:, -1]
print(arr2d_slice)

[3 6 9]


In [56]:
arr2d_slice = arr2d[1, -2:]
print(arr2d_slice)

[5 6]
